In [1]:
import pandas as pd

In [2]:
deployed_sensors = pd.read_json('deployed_sensors_directus.json')

In [3]:
display(deployed_sensors)

,deployment_id,dev_id,name,sensor_status,date_updated,deploy_type,date_deployed,requested_by
0,good_yellow_stingray,fs5-00434,BX - Van Cortlandt Park Nature Trail,good,NaN,pluvial,2026-06-10T11:13:00,None
1,delightfully-mischievous-alpaca,fs5-00467,BK - Avenue L/E 24th St,good,NaN,pluvial,2026-06-05T16:02:00,None
2,curiously-brisk-hedgehog,fs5-00475,BK - 14th Ave/44th St,good,NaN,pluvial,2026-06-05T15:55:00,None
3,elegantly-rustic-fox,fs5-00464,BK - Rugby Rd/Cortelyou Rd,good,NaN,pluvial,2026-06-05T15:46:00,None
4,unexpectedly-drowsy-penguin,fs5-00410,BK - E Eighth St/Kermit Pl,good,NaN,pluvial,2026-06-05T15:35:00,None
...,...,...,...,...,...,...,...,...
410,daily_gentle_beetle,fs-00002,BK - 4th Av/Garfield Pl,good,2026-01-13T17:42:23.534Z,pluvial,2021-07-15T00:00:00,[internal]
411,weekly_poetic_guinea,fs3-00158,BK - Carroll St/4th Av,good,2026-01-09T17:36:58.840Z,pluvial,2021-07-15T00:00:00,[internal]
412,mildly_calm_ibex,fs-00006,Q - Davenport Ct 1,noisy,2026-05-27T18:52:59.571Z,coastal,2021-03-05T00:00:00,[community]
413,duly_pro_vervet,fs3-00379,Q - Russell St 1,dead,2026-05-26T18:25:41.848Z,coastal,2021-03-05T00:00:00,[community]
414,daily_new_falcon,fs-00005,BK - Hoyt St/5th St,good,2026-01-09T17:45:26.944Z,pluvial,2020-10-05T00:00:00,[]

In [4]:
display(deployed_sensors['deploy_type'].unique())

<StringArray>
['pluvial', 'coastal']
Length: 2, dtype: str

In [5]:
coastal_sensors = deployed_sensors[deployed_sensors['deploy_type'] == 'coastal']

In [6]:
display(coastal_sensors.head())
print(coastal_sensors.shape)

,deployment_id,dev_id,name,sensor_status,date_updated,deploy_type,date_deployed,requested_by
10,notably-causal-goshawk,fs5-00487,SI - Boundary Ave/ Lincoln Ave,low_charge,2026-06-09T14:51:10.267Z,coastal,2026-05-29T10:52:00,[Ricardo]
11,multiply-well-giraffe,fs5-00481,SI - Midland Ave/ Boundary Ave,good,2026-06-02T19:06:03.663Z,coastal,2026-05-29T10:47:00,[Ricardo]
20,visually-endless-martin,fs5-00614,SI - Boundary Ave/Hamden Ave,good,2026-05-11T19:39:58.905Z,coastal,2026-05-08T12:00:00,None
21,verbally-ultimate-elf,fs5-00740,SI - Nugent Ave/Quintard St,good,2026-05-19T19:56:25.031Z,coastal,2026-05-08T11:55:00,None
22,previously-bursting-bird,fs5-00651,SI - Sand Ln/Sunnymeade Village,good,2026-05-19T19:58:40.039Z,coastal,2026-05-08T11:50:00,None

(51, 8)

In [7]:
# store coastal sensor dataset for use in the FloodNet_Sensor_Locations notebook
%store coastal_sensors

Stored 'coastal_sensors' (DataFrame)

In [9]:
deployed_sensors[deployed_sensors['deploy_type'].isna()]

Empty DataFrame
Columns: [deployment_id, dev_id, name, sensor_status, date_updated, deploy_type, date_deployed, requested_by]
Index: []